################################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza             #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
services:
  phpinfo:
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
        reservations:
          cpus: "0.1"
          memory: 100M
    expose:
    - "8080"
    healthcheck:
      interval: 10s
      retries: 3
      start_period: 30s
      test: php -r "print file_get_contents('http://localhost:8080/');"
      timeout: 1s
    image: academiaonline/phpinfo:2.1
    ports:
    - "80:8080"
version: "3.8"
################################################################################
