#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpinfo
  template:
    metadata:
      labels:
        app: phpinfo
    spec:
      containers:
      -
        name: phpinfo
        image: academiaonline/phpinfo:v2.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
        ports:
          - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 100M
          requests:
            cpu: 100m
            memory: 100M
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: phpinfo
spec:
  podSelector:
    matchLabels:
      app: phpinfo
  ingress:
    - ports:
        - port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: phpinfo
spec:
  ports:
    - port: 80
      nodePort: 30000
      targetPort: 8080
  selector:
    app: phpinfo
  type: NodePort
---
